version: '3'

services:
  deepseek-free-api:
    container_name: deepseek-free-api
    image: vinlic/deepseek-free-api:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Shanghai
      - DEEP_SEEK_CHAT_AUTHORIZATION=7Vg2hS7yH4ozSe1jrJDSBvVGcmx/xlutMHOTHoFwaQrb8mBfRnNKcSHVB4s2+P/G
    extra_hosts: # <--- 添加 extra_hosts 部分
      - chat.deepseek.com:104.18.27.90
      - chat.deepseek.com:104.18.26.90

